[package]
name = "ircgrep"
version = "0.1.0"
authors = ["Øystein Walle <oystwa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
colored = "1.9.0"
circular-queue = "0.2.2"
clap = "2.33"
